[build]
  command = "cd frontend && yarn install && yarn build && curl -X POST https://speako-kor.netlify.app/.netlify/functions/trigger-github-actions"
  publish = "frontend/dist"

[functions]
  directory = "backend/netlify/functions"