[build]
  command = "yarn install && yarn build && curl -X POST https://speako-kor.netlify.app/.netlify/functions/trigger-github-actions"
  publish = "dist"

[functions]
  directory = "netlify/functions"