name: Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          yarn install

      - name: Build
        run: |
          cd frontend
          yarn build
        env:
          NODE_ENV: production

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify and extract deploy ID
        id: deploy
        run: |
          cd frontend
          DEPLOY_JSON=$(netlify deploy --prod --dir=dist --json \
            --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID)
          echo "$DEPLOY_JSON"
          
          DEPLOY_ID=$(echo "$DEPLOY_JSON" | jq -r '.deploy_id')
          echo "Deploy ID: $DEPLOY_ID"
          echo "Netlify Deploy Log: https://app.netlify.com/sites/$NETLIFY_SITE_NAME/deploys/$DEPLOY_ID"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_SITE_NAME: ${{ secrets.NETLIFY_SITE_NAME }}

      - name: Check for deployment errors
        if: failure()
        run: |
          echo "::error::Deployment failed. Check Netlify logs for details."
          echo "Deploy Log URL: https://app.netlify.com/sites/$NETLIFY_SITE_NAME/deploys/${{ steps.deploy.outputs.deploy_id }}"
        env:
          NETLIFY_SITE_NAME: ${{ secrets.NETLIFY_SITE_NAME }} 