name: Netlify Build Log Fetch

on:
  repository_dispatch:
    types: [netlify-build-complete]

jobs:
  fetch-log:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest Netlify deploy log
        run: |
          DEPLOY_ID=$(curl -s -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
            "https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys" | jq -r '.[0].id')
          echo "Latest Deploy ID: $DEPLOY_ID"
          curl -s -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
            "https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys/$DEPLOY_ID/logs" | jq -r '.logs'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 